name: ff_commons
description: FlutterFlow Commons Package

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  munday:
    path: ../../
  collection: 1.19.1
  equatable: 2.0.7
  http: 1.4.0
  mime_type: 1.0.0

dependency_overrides:
  http: 1.4.0
  intl: 0.20.2
  uuid: ^4.0.0


flutter:
